steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cellular-axon-325108/flask-hello-ihab-ci-cd:latest','.']
images: [gcr.io/cellular-axon-325108/flask-hello-ihab-ci-cd:latest]